### PR TITLE
remove google maps key

### PR DESCRIPTION
**Pull request by rudymichal**
@cmwd 
@magul

### CODE REVIEW

**Comment by magul** [comment]
I actually prefer settings.js over cofnig.js nad suffix .example over .back. And btw travis build is failing so i believe you need to provide this file with key during building there.

**Comment by magul** [comment]
And do we really need to stare these values in json? I was actually thinking about proper js module.

**Comment by magul** [comment]
But nevertheless good work!

**Comment by cmwd** [comment]
So the main problem which I see in this implementation is that we are forcing users to compile engine with own settings file rather than allow they to pass settings through constructor. I didn't saw this problem at first - probably because of beers :)
I think we should take step back and move whole logic into gulpfile.

My proposal is to replace google key with some sort of string tag e.g:

``` javascript
const plantingInstance = new Plantingjs({
  googleApiKey: '<GOOGLE_API_KEY_HERE>'
});
```

Then pass those example html files through gulp and replace `<GOOGLE_API_KEY_HERE>` with actual key. Because we need it only for development purposes we can use environment variable for storing development key or for sake of convenience move settings file into application root and read it from there (if exists).

> And do we really need to stare these values in json? I was actually thinking about proper js module.

In this case it doesn't really matter. But it's good practice to use proper data formats for storing informations. If you have some dynamic settings you can easily serialize it to JSON :)

**Pull request closed without merging**
